name: MakiScreen
description: Stream an MJPEG stream to Minecraft maps!
version: 1.1.3
main: cat.maki.MakiScreen.MakiScreen
load: POSTWORLD
commands:
  maki:
    description: Manage MakiScreen
    usage: /<command>